- image:
    registry: docker.io
    repository: cogatedemo/calculator-client

- deployment:
    name: deploy-calculator
    images:
      - docker.io/cogatedemo/calculator-client
      - docker.io/cogatedemo/calculator-server
    platform: k8s-1-node
    apply:
      path: deploy.yaml
      wait:
        resource: job/calculator-client
        for: condition=complete
        timeout: 60s

